services:
  db:
    image: postgres:latest
    container_name: ohmygit_db
    environment:
      POSTGRES_DB: ohmygit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
    container_name: ohmygit_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - internal

  backend:
    build:
      context: ./backend
    container_name: ohmygit_backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/ohmygit
      RUST_LOG: debug
    command: ["sh", "-c", "wait-for-it db:5432 -- /bin/backend"]
    networks:
      - internal
    volumes:
      - ./git_repos:/repos

volumes:
  pgdata:

networks:
  internal:
    driver: bridge
    #driver_opts:
      #com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"