services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    labels:
      - com.github.nginx-proxy.nginx-proxy=true
    environment:
      - ENABLE_IPV6=false
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deployment/certs:/etc/nginx/certs:ro
      - ./deployment/vhost.d:/etc/nginx/vhost.d
      - ./deployment/html:/usr/share/nginx/html
    networks:
      - web

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    environment:
      DEFAULT_EMAIL: paulschilling@posteo.de
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deployment/certs:/etc/nginx/certs
      - ./deployment/vhost.d:/etc/nginx/vhost.d
      - ./deployment/html:/usr/share/nginx/html
    networks:
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: prod/Dockerfile
    container_name: ohmygit_frontend
    environment:
      - VIRTUAL_HOST=ohmygit.site,www.ohmygit.site
      - LETSENCRYPT_HOST=ohmygit.site,www.ohmygit.site
      - LETSENCRYPT_EMAIL=paulschilling@posteo.de
    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ohmygit_backend
    environment:
      - VIRTUAL_HOST=git.ohmygit.site
      - LETSENCRYPT_HOST=git.ohmygit.site
      - LETSENCRYPT_EMAIL=paulschilling@posteo.de
      - DATABASE_URL=postgres://admin:password@db:5432/ohmygit
    depends_on:
      - db
    command: ["sh", "-c", "/bin/wait-for-it.sh db:5432 -- /bin/backend"]
    volumes:
      - ./git_repos:/repos
    networks:
      - web
      - internal

  db:
    image: postgres:latest
    container_name: ohmygit_db
    environment:
      POSTGRES_DB: ohmygit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pgdata:
  certs:
  vhost.d:
  html:

networks:
  web:
  internal:
