[package]
name = "templating"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }

askama = { version = "0.14.0", features = ["serde_json"] }
serde = { version = "1.0.219", features = ["derive"] }