drop table merge_requests;
drop table comments;
drop table user_repository_roles;
drop table organizations_members;
drop table issues;
drop table branches;
drop table repositories;
drop table organizations;
drop table users;
drop function if exists update_updated_at_column() cascade;